-- Quizlatro Question Decks
-- Each deck is { name = "...", questions = { {q, a}, ... } }
-- Wrong answer choices are drawn only from questions within the same deck.
-- Each deck must have at least 4 questions.

return {
    {
        name = "Hiragana to Romaji",
        questions = {
            { q = "あ", a = "a" },
            { q = "い", a = "i" },
            { q = "う", a = "u" },
            { q = "え", a = "e" },
            { q = "お", a = "o" },
            { q = "か", a = "ka" },
            { q = "き", a = "ki" },
            { q = "く", a = "ku" },
            { q = "け", a = "ke" },
            { q = "こ", a = "ko" },
            { q = "さ", a = "sa" },
            { q = "し", a = "shi" },
            { q = "す", a = "su" },
            { q = "せ", a = "se" },
            { q = "そ", a = "so" },
            { q = "た", a = "ta" },
            { q = "ち", a = "chi" },
            { q = "つ", a = "tsu" },
            { q = "て", a = "te" },
            { q = "と", a = "to" },
            { q = "な", a = "na" },
            { q = "に", a = "ni" },
            { q = "ぬ", a = "nu" },
            { q = "ね", a = "ne" },
            { q = "の", a = "no" },
            { q = "は", a = "ha" },
            { q = "ひ", a = "hi" },
            { q = "ふ", a = "fu" },
            { q = "へ", a = "he" },
            { q = "ほ", a = "ho" },
            { q = "ま", a = "ma" },
            { q = "み", a = "mi" },
            { q = "む", a = "mu" },
            { q = "め", a = "me" },
            { q = "も", a = "mo" },
            { q = "や", a = "ya" },
            { q = "ゆ", a = "yu" },
            { q = "よ", a = "yo" },
            { q = "ら", a = "ra" },
            { q = "り", a = "ri" },
            { q = "る", a = "ru" },
            { q = "れ", a = "re" },
            { q = "ろ", a = "ro" },
            { q = "わ", a = "wa" },
            { q = "を", a = "wo" },
            { q = "ん", a = "n" },
        }
    },
    {
        name = "Romaji to Hiragana",
        questions = {
            { q = "a", a = "あ" },
            { q = "i", a = "い" },
            { q = "u", a = "う" },
            { q = "e", a = "え" },
            { q = "o", a = "お" },
            { q = "ka", a = "か" },
            { q = "ki", a = "き" },
            { q = "ku", a = "く" },
            { q = "ke", a = "け" },
            { q = "ko", a = "こ" },
            { q = "sa", a = "さ" },
            { q = "shi", a = "し" },
            { q = "su", a = "す" },
            { q = "se", a = "せ" },
            { q = "so", a = "そ" },
            { q = "ta", a = "た" },
            { q = "chi", a = "ち" },
            { q = "tsu", a = "つ" },
            { q = "te", a = "て" },
            { q = "to", a = "と" },
            { q = "na", a = "な" },
            { q = "ni", a = "に" },
            { q = "nu", a = "ぬ" },
            { q = "ne", a = "ね" },
            { q = "no", a = "の" },
            { q = "ha", a = "は" },
            { q = "hi", a = "ひ" },
            { q = "fu", a = "ふ" },
            { q = "he", a = "へ" },
            { q = "ho", a = "ほ" },
            { q = "ma", a = "ま" },
            { q = "mi", a = "み" },
            { q = "mu", a = "む" },
            { q = "me", a = "め" },
            { q = "mo", a = "も" },
            { q = "ya", a = "や" },
            { q = "yu", a = "ゆ" },
            { q = "yo", a = "よ" },
            { q = "ra", a = "ら" },
            { q = "ri", a = "り" },
            { q = "ru", a = "る" },
            { q = "re", a = "れ" },
            { q = "ro", a = "ろ" },
            { q = "wa", a = "わ" },
            { q = "wo", a = "を" },
            { q = "n", a = "ん" },
        }
    }
}
